packages:
#  - "packages/*"
  - "packages/dataset"
  - "packages/onchain"
  - "packages/services"
  - "packages/subgraph"
  - "packages/webui"
  # Exclude packages that are inside test directories
  - '!**/test/**'
